apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpod-deployment
  namespace: dpod-api
  labels:
    app: dpod-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpod-api
  template:
    metadata:
      labels:
        app: dpod-api
    spec:
      shareProcessNamespace: true
      containers:
      - name: dpod-api
        image: docker.repo.eng.netapp.com/global/devts-daas/dpod-python3.10:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
